### PR TITLE
92 node updates

### PR DESCRIPTION
**Pull request by edavalosanaya**
PR related to Issue #92 

* Refactored the state information into proper `dataclasses` for `Manager`, `Worker`, and `Node`
    * Updated cluster orchestration methods (e.g. `commit`, `gather`, `collect`) to use the new state `dataclasses`
    * Updated `GET /network` route to return JSON of `ManagerState`, which includes all `WorkerState` and `NodeState`
    * Updated test to use the new state variables
    * Made state attributes accessible through Python decorators (to avoid having to access  like this:`manager.state.ip`)
* Changed the WS communication to use JSON format instead of pickled python objects (needed to make JS talk to Python)
    * Added JSON methods for `DataChunk` to make `gather` method work, mostly for cluster testing
    * Removed unused Enums
* Made Node updates rely from Worker to Manager, and Manager to WS clients (front-end)
    * Added testing in `test/front_end_integration/test_ws.py`

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
One suggestion, I looked at the changes briefly. I think it would make sense to divide this work into three separate Issues/ Pull requests. 

1. First, let's define a network state that can be broadcast or queried from the API. This would mean, taking the data classes that we have here and extending them with configuration from the Logging changes made in #99. Something like a schema defined in https://github.com/oele-isis-vanderbilt/ChimeraPy/discussions/87#discussioncomment-5000757 might be helpful for thinking about and deliberating for this PR. The existing endpoints might be used to test this.

3. Second, make sure that we have the correct protocol for communicating the states back and forth. This would mean changing the current pickle approach and replacing them with JSON.

4. Third, work on the status broadcast issues and eventually refactor the current endpoints defined for controlling/ monitoring the cluster into a separate module.

This is a manageable set of changes that I think separate concerns a bit and will be tractable.

**Comment by edavalosanaya** [comment]
> One suggestion, I looked at the changes briefly. I think it would make sense to divide this work into three separate Issues/ Pull requests.
> 
> 1. First, let's define a network state that can be broadcast or queried from the API. This would mean, taking the data classes that we have here and extending them with configuration from the Logging changes made in [Optionally publish `Manager` logs via `ZMQLogHander`. Closes #97 #99](https://github.com/oele-isis-vanderbilt/ChimeraPy/pull/99). Something like a schema defined in [Development RoadMap for ChimeraPy-Dashboard/ API Planning #87 (comment)](https://github.com/oele-isis-vanderbilt/ChimeraPy/discussions/87#discussioncomment-5000757) might be helpful for thinking about and deliberating for this PR. The existing endpoints might be used to test this.
> 2. Second, make sure that we have the correct protocol for communicating the states back and forth. This would mean changing the current pickle approach and replacing them with JSON.
> 3. Third, work on the status broadcast issues and eventually refactor the current endpoints defined for controlling/ monitoring the cluster into a separate module.
> 
> This is a manageable set of changes that I think separate concerns a bit and will be tractable.

I agree with you, best to split into separate PR. How do we do this? Not sure how to split a PR into multiple.

**Comment by umesh-timalsina** [comment]
You can do your best to cherrypick. But, I think its best to keep this branch up in GitHub and reorganize the changes mentioned above by looking at the branch and taking it from there.

**Comment by edavalosanaya** [comment]
This PR was broken down into smaller PRs: #104, #105, #115, and #116.

**Pull request closed without merging**
